services:
  - type: web
    name: amazon-seller-parser
    env: node
    plan: free
    buildCommand: npm install
    prebuildCommand: npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
